name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Disable Swift Package Manager migration
        run: echo "FLUTTER_SUPPRESS_MIGRATIONS=true" >> $GITHUB_ENV

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Force iOS 14.0 Platform in Podfile
        run: |
          PODFILE="ios/Podfile"
          mkdir -p ios
          cat << 'EOF' > "$PODFILE"
          platform :ios, '14.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'
          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }
          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first"
            end
            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found"
          end
          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
          flutter_ios_podfile_setup
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          post_install do |installer|
            installer.generated_projects.each do |project|
              project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                end
              end
            end
          end
          EOF

      - run: flutter pub get

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app/ Payload
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/Payload/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Automatic iOS Build release"
